import type { Locale } from "@/i18n/config";
import { formatCalendarDate } from "./date-utils";
import type { Assignment } from "./types";

function groupedAssignmentLines(assignment: Assignment, currentUserDisplayName: string): string[] {
  const namesByRole = new Map<string, string[]>();
  const addName = (role: string, name: string) => {
    const names = namesByRole.get(role) ?? [];
    names.push(name);
    namesByRole.set(role, names);
  };

  addName(assignment.role, currentUserDisplayName);
  for (const teammate of assignment.teammates) {
    addName(teammate.role, teammate.displayName);
  }

  return [...namesByRole.entries()].map(([role, names]) => `${role}: ${names.join(", ")}`);
}

function songLines(assignment: Assignment): string | null {
  if (assignment.songs.length === 0) return null;
  return assignment.songs
    .map((song, index) => {
      const line = `${index + 1}. ${song.title}`;
      return song.youtubeLink ? `${line}\n   🎥 ${song.youtubeLink}` : line;
    })
    .join("\n");
}

/**
 * Builds a copy-pasteable WhatsApp reminder for one of the current user's
 * upcoming assignments, mirroring the legacy SJSM_Music
 * WhatsAppTemplateGenerator's format (date/time/team/songs/printing link).
 * Generated in the viewer's own UI locale - this app has no separate
 * per-roster or per-recipient locale to draw from.
 */
export function buildWhatsAppMessage(
  assignment: Assignment,
  currentUserDisplayName: string,
  locale: Locale,
): string {
  const date = formatCalendarDate(assignment.serviceDate, locale);
  const assignmentLines = groupedAssignmentLines(assignment, currentUserDisplayName);
  const songs = songLines(assignment);

  if (locale === "zh") {
    return [
      "📅 *服侍提醒*",
      "",
      `*日期：* ${date}`,
      `*时间：* ${assignment.serviceTime}`,
      `*服侍：* ${assignment.title}`,
      "",
      "*服侍人员安排：*",
      ...assignmentLines.map((line) => `• ${line}`),
      ...(songs ? ["", "*敬拜歌曲：*", songs] : []),
      ...(assignment.songsPrintingLink ? ["", `📄 *歌曲打印链接：* ${assignment.songsPrintingLink}`] : []),
      "",
      "🙏 请各位服侍人员准时到场，谢谢！",
      "",
      "_此消息由 SJSM SmartRoster 生成_",
    ].join("\n");
  }

  return [
    "📅 *Service Reminder*",
    "",
    `*Date:* ${date}`,
    `*Time:* ${assignment.serviceTime}`,
    `*Service:* ${assignment.title}`,
    "",
    "*Team Assignments:*",
    ...assignmentLines.map((line) => `• ${line}`),
    ...(songs ? ["", "*Worship Songs:*", songs] : []),
    ...(assignment.songsPrintingLink ? ["", `📄 *Printable Songs Link:* ${assignment.songsPrintingLink}`] : []),
    "",
    "🙏 Please arrive on time. Thank you!",
    "",
    "_Generated by SJSM SmartRoster_",
  ].join("\n");
}
